### PR TITLE
local dev keys expired

### PR DESCRIPTION
**Pull request by eriktaubeneck**
these are only used for local dev, and the old ones expired

## Summary by CodeRabbit

- **New Features**
	- Updated cryptographic keys and certificates for enhanced security and authentication processes.
  
- **Bug Fixes**
	- Resolved potential issues related to outdated keys that could affect secure communications.

- **Chores**
	- Modified key values and configurations to comply with updated security protocols and standards.

### CODE REVIEW

**Comment by cberkhoff** [comment]
Do we need to have this keys in CI?

**Review by cberkhoff — APPROVED** [review]
I'm ok updating but I wonder if we need to keep doing this

**Comment by akoshelev** [comment]
there is a way to generate them with 2+ year expiration, maybe for local dev it is enough

**Review by akoshelev — APPROVED** [review]

**Comment by eriktaubeneck** [comment]
> Do we need to have this keys in CI?

it's not for CI, it's just for local dev. you could have the user generate them on their own, but then you also have to have them build the network.toml file too. local dev doesn't need to be secure so this makes setup easier.


> there is a way to generate them with 2+ year expiration, maybe for local dev it is enough
good call out. let me push one with longer expiration

**Pull request merged**
